### ISSUE TITLE
colcon build error

### ISSUE THREAD

**Issue by Baldins** [Unity-Technologies/Unity-Robotics-Hub#346]
Hello, 

I am getting the following error with colcon build - does someone can help?

lambda-rl@lambda-dual:~/dev_ws$ source install/setup.bash 
ROS_DISTRO was set to 'foxy' before. Please make sure that the environment does not mix paths from different distributions.
ROS_DISTRO was set to 'noetic' before. Please make sure that the environment does not mix paths from different distributions.
[connext_cmake_module] Warning: The location at which Connext was found when the workspace was built [[/opt/rti.com/rti_connext_dds-5.3.1]] does not point to a valid directory, and the NDDSHOME environment variable has not been set. Support for Connext will not be available.
lambda-rl@lambda-dual:~/dev_ws$ colcon build
[0.136s] WARNING:colcon.colcon_core.verb:Some selected packages are already built in one or more underlay workspaces:
	'turtlesim' is in: /home/lambda-rl/dev_ws/install/turtlesim, /home/lambda-rl/ros2_foxy/ros2-linux, /opt/ros/foxy
If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at run time.
If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at run time may occur.

If you understand the risks and want to override a package anyways, add the following to the command line:
	--allow-overriding turtlesim

This may be promoted to an error in a future release of colcon-core.
Starting >>> ros_tcp_endpoint
Starting >>> turtlesim
Finished <<< turtlesim [0.82s]                                       
--- stderr: ros_tcp_endpoint                         
Traceback (most recent call last):
  File "/home/lambda-rl/dev_ws/build/ros_tcp_endpoint/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/home/lambda-rl/dev_ws/build/ros_tcp_endpoint/devel/env.sh')
  File "/opt/ros/noetic/lib/python3/dist-packages/catkin/environment_cache.py", line 63, in generate_environment_script
    env_after = ast.literal_eval(output.decode('utf8'))
  File "/usr/lib/python3.8/ast.py", line 59, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    ROS_DISTRO was set to 'foxy' before. Please make sure that the environment does not mix paths from different distributions.
               ^
SyntaxError: invalid syntax
CMake Error at /opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python3
  "/home/lambda-rl/dev_ws/build/ros_tcp_endpoint/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/all.cmake:208 (safe_execute_process)
  /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)

---
Failed   <<< ros_tcp_endpoint [1.33s, exited with code 1]

Summary: 1 package finished [1.42s]
  1 package failed: ros_tcp_endpoint
  1 package had stderr output: ros_tcp_endpoint

**Comment by LaurieCheers-unity** [comment]
Just as it says, your environment seems to contain a mixture of Foxy (ROS 2) and Noetic (ROS 1). Since you're doing colcon build I assume you want ROS 2 - try uninstalling Noetic?
