### ISSUE TITLE
Continuously connecting and disconnecting while throwing exceptions on server side

### ISSUE THREAD

**Issue by krajFHI** [Unity-Technologies/Unity-Robotics-Hub#408]
I am just trying to setup up an initial connection to start working with this project, but when I start the connection from Unity Editor, this following pattern keeps repeating on the server side while steadily connecting and disconnecting to host.

```[INFO] [1699441005.163017847] [UnityEndpoint]: Connection from 192.168.0.171
[INFO] [1699441005.167617580] [UnityEndpoint]: Disconnected from 192.168.0.171
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/user/ros2_tcp/install/ros_tcp_endpoint/lib/python3.10/site-packages/ros_tcp_endpoint/client.py", line 213, in run
    self.tcp_server.handle_syscommand(destination, data)
  File "/home/user/ros2_tcp/install/ros_tcp_endpoint/lib/python3.10/site-packages/ros_tcp_endpoint/server.py", line 126, in handle_syscommand
    params = json.loads(message_json)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 51 (char 50)
```

I am using the following setup:

- Unity Version: [e.g. Unity 2021.3.4f1]
- Unity machine OS + version: Windows 10
- ROS machine OS + version: Ubuntu 22.04, ROS Humble
- ROS–Unity communication: cloned repository and built with colcon (no docker)
- Branch or version: v0.7.0

**Comment by krajFHI** [comment]
Sorry, I found the error that I didnt switch to ROS2 settings in Unity even though I was sure to have done it. Please delete this issue. Thanks
